<?php
    
    echo "<h1>Administración</h1>";

    foreach ($pubs as $pub)
    {
        echo "<div class='pub'>";
        echo "<h3>" . $pub->getTitle() . "</h3>";
        echo "<p>" . $pub->getText() . "</p>";
        echo "<h4> ID:" . $pub->getId() . "</h4>";
        echo "<a href='index.php?admin=1&editid=".$pub->getId()."'>Editar</a>";
        echo "</div>";
    }
        echo "<h3><a href='index.php?logout=1'>Cerrar sesión</a></h3>";
        echo "<h3><a href='index.php?newPub=1'>Nueva publicación</a></h3>";
        echo "<h3><a href='index.php?admin=1&usermode=true'>Administrar usuarios</a></h3>";
        
   if (!isset($_SESSION['user']) || !($_SESSION['user']->getRol()) > 1)
   {
    header("Location: index.php");
   }





?>