<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administración de usuarios</title>
    <style>
      div {
        border: 0.2rem solid black;
        padding: 0.5rem;
        margin: 0.5rem;
      }
      .usuario {
        font-size: larger;
      }
    </style>
</head>
<body>
    <?php
      $db = Conectar::conexion();
      $q = "SELECT * FROM usuarios;";
      $result = $db->query($q);
      while ($row = $result->fetch_assoc())
      {
        echo "<div>";
        echo "<p class='usuario'>Usuario: <u>" . $row['username'] . "</u></p><p> Rol: " . $row['rol'] . "</p>";
        echo "<a href='index.php?admin=1&deleteuser=". $row['id'] ."'>Banear</a>";
        echo "</div>";
      }
    ?>
    <br>
    <a href="index.php?admin=1">Volver al modo administrador</a>
</body>
</html>