<?php

    echo "<h1>Iniciar sesión</h1>";
    echo "<h3>No tienes una cuenta? <a href='index.php?register=1'>Regístrate</a></h3>";
    echo "<h3>O puedes usar el <a href='index.php?guestMode=true'>modo invitado</a> </h3>";
    echo '<form method="post" action="index.php">
            <input type="text" name="username" placeholder="Nombre de usuario" required><br>
            <input type="password" name="password" placeholder="Contraseña" required><br>
            <input type="submit" value="Iniciar sesión">
            </form>';
?>
