<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publicaciones</title>
    <style>
        div {
            border: 0.2rem solid black;
            padding: 0.5rem;
            margin: 0.5rem;
            background-color: #aee;
        }
        .pub {
            font-size: larger;
            cursor: pointer;
        }
        body {
            background-color: #eee;
        }
        form
        {
            display: flex;
            flex-direction: column;
            width: 20%;
            top : 0;
            position: fixed;
            right: 0;
        }
        label
        {
            font-weight: bold;
        }
        input, textarea
        {
            margin-bottom: 1rem;
            background-color: #eee;
        }
        input[type="submit"]
        {
            background-color: rgb(110, 7, 38);
            color: #fff;
            border: none;
            padding: 1rem;
            cursor: pointer;
        }
    </style>
</head>
<body>
<?php
    
    echo "<h1>Publicaciones</h1>";
    echo "<form action='index.php?search=true' method='post'>";
    echo "<input type='text' name='search' id='search'>";
    echo "<input type='submit' value='Buscar'>";
    echo "</form>";
    foreach ($pubs as $pub)
    {
        echo "<div class='pub'>";
        echo "<h3>" . $pub->getTitle() . "</h3>";
        echo "<p>" . $pub->getText() . "</p>";
        echo "<a href='index.php?seePub=".$pub->getId()."'>Comentar</a>";
        echo "</div>";
    }

   if (isset($_SESSION['user']))
   {
        echo "<h3><a href='index.php?logout=1'>Cerrar sesión</a></h3>";
        echo "<h3><a href='index.php?newPub=1'>Nueva publicación</a></h3>";
        if (($_SESSION['user']->getRol()) > 1)
        {
            // Redirigir al modo admin
            echo "<h3><a href='index.php?admin=1'>Modo admin</a></h3>";
        }
   }
   else
   {
        echo "<h3><a href='index.php'>Iniciar sesión</a></h3>";
   }

?>
</body>
</html>
