<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear publicación</title>
    <style>
        form
        {
            display: flex;
            flex-direction: column;
            width: 50%;
            margin: 0 auto;
        }
        label
        {
            font-weight: bold;
        }
        input, textarea
        {
            margin-bottom: 1rem;
            background-color: #eee;
        }
        input[type="submit"]
        {
            background-color: rgb(110, 7, 38);
            color: #fff;
            border: none;
            padding: 1rem;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <form action="index.php?newPub=2" method="post">
        <label for="titulo">Título</label>
        <input type="text" name="titulo" id="titulo">
        <label for="texto">Texto</label>
        <textarea name="texto" id="texto" cols="30" rows="10"></textarea>
        <input type="submit" value="Crear">
    </form>
</body>
</html>