<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login!</title>
</head>
<body>
    <form action="index.php" method="post">
        <input type="text" name="user" id="user" placeholder="Nombre de usuario" required>
        <input type="password" name="password" id="password" placeholder="Contraseña" required>
        <input type="submit" value="Iniciar sesión">
</body>
</html>